name: kahani_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.2
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  dio: ^5.9.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.1
  dotted_border: ^3.1.0
  sign_in_with_apple: ^7.0.1
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.jpg"
  adaptive_icon_background: "#023BB0" # optional â€” change to your theme color
  adaptive_icon_foreground: "assets/icons/logo.jpg"
