name: kahani_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.2
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
