name: kahani_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11
  convex_bottom_bar: ^3.2.0
  google_fonts: ^6.2.1 # Add this line
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.2
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  dio: ^5.9.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.1
  sign_in_with_apple: ^7.0.1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  material_symbols_icons: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  test: ^1.26.3
  mockito: ^5.4.4


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # FIX: Remove the local fonts section

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.jpg"
  adaptive_icon_background: "#023BB0"
  adaptive_icon_foreground: "assets/icons/logo.jpg"
